# Cross-package fixture contract guard.
#
# JStats / Carm (npm "carm") and the validation runner ship ~1010 JSON fixtures
# generated by `Saqrlab::simulate_data(type, seed = i)` for
#   type in {ttest, anova, correlation, clusters, factor_analysis, prediction}
# over seeds 1..1000 (see <JStats>/validation/r-reference/*-ref.R).
#
# Those fixtures are checked into the consumer repos and compared byte-for-byte
# (12-significant-digit JSON) by their numerical-equivalence tests. If
# simulate_data()'s RNG stream, structural-parameter derivation, or column
# layout drifts for a fixed seed, 100% of those downstream tests break while
# Saqrlab's own suite would otherwise stay green.
#
# This file is the tripwire: it pins the EXACT output of the fixture-generating
# calls (helpers + golden reference in helper-fixture-contract.R /
# fixtures/fixture-contract-golden.rds) so any such drift fails HERE first.
#
# If you INTENTIONALLY change simulate_data() and these comparisons fail, you
# must (a) regenerate the consumer fixtures in lockstep by re-running
# <JStats>/validation/r-reference/*-ref.R, and (b) regenerate this golden:
#   source("tests/testthat/helper-fixture-contract.R")
#   saveRDS(build_fixture_fingerprints(),
#           "tests/testthat/fixtures/fixture-contract-golden.rds", version = 2)

test_that("simulate_data() preserves the fixture column contract per type", {
  for (ty in names(fixture_contract)) {
    d <- simulate_data(ty, seed = 1)
    expect_s3_class(d, "data.frame")
    expect_identical(
      names(d), fixture_contract[[ty]],
      info = sprintf("column contract drifted for type '%s'", ty)
    )
  }
})

test_that("simulate_data() is reproducible for a fixed seed (fixture seeds)", {
  for (ty in names(fixture_contract)) {
    for (s in c(1L, 2L, 100L)) {
      expect_identical(
        simulate_data(ty, seed = s),
        simulate_data(ty, seed = s),
        info = sprintf("non-reproducible output for type '%s' seed %d", ty, s)
      )
    }
  }
})

test_that("simulate_data() output is byte-stable vs golden (fixture contract)", {
  golden_path <- fixture_golden_path()
  expect_true(
    file.exists(golden_path),
    info = "golden reference missing; regenerate per the header of this file"
  )
  golden <- readRDS(golden_path)
  current <- build_fixture_fingerprints()

  # Same set of pinned cases.
  expect_identical(sort(names(current)), sort(names(golden)))

  # Every fixture-generating call must reproduce its golden fingerprint exactly.
  for (key in names(golden)) {
    expect_identical(
      current[[key]], golden[[key]],
      info = sprintf(
        "simulate_data() output drifted for '%s' -- this WILL break the JStats/Carm fixtures. See file header to regenerate intentionally.",
        key
      )
    )
  }
})
